"""Report generation engines for AlphaSwarm."""

from alphaswarm.models import ConsensusVerdict, MarketData, Stance


def generate_markdown_report(verdict: ConsensusVerdict, market_data: MarketData) -> str:
    ind = market_data.indicators
    lines = [
        f"# ⚡ AlphaSwarm Intelligence Dossier: {verdict.symbol}",
        "",
        f"> **Generated:** {verdict.generated_at}  ",
        f"> **Market Price:** ${verdict.market_price:,.2f} ({market_data.change_24h_pct:+.2f}%)  ",
        f"> **Consensus Stance:** `{verdict.final_stance.value}` ({verdict.confidence_score}% Conviction)  ",
        f"> **Key Invalidation (Stop):** ${verdict.key_invalidation_level:,.2f}  ",
        f"> **Time Horizon:** `{verdict.time_horizon}`",
        "",
        "---",
        "",
        "## 🎯 Primary Consensus Thesis",
        verdict.primary_thesis,
        "",
        "### 🐂 Bull Case Argument",
        verdict.bull_case,
        "",
        "### 🐻 Bear Case / Downside Risks",
        verdict.bear_case,
        "",
        "---",
        "",
        "## 📊 Technical Indicator Ground-Truth",
        "",
    ]

    if ind:
        lines.extend([
            "| Indicator | Value | Interpretation |",
            "|---|---|---|",
            f"| **RSI (14)** | `{ind.rsi_14:.2f}` | {'Oversold (<30)' if ind.rsi_14 < 30 else 'Overbought (>70)' if ind.rsi_14 > 70 else 'Neutral'} |",
            f"| **50 / 200 SMA** | `${ind.sma_50:,.2f}` / `${ind.sma_200:,.2f}` | `{ind.trend_50_200}` |",
            f"| **Bollinger Bands** | `${ind.bollinger_lower:,.2f}` – `${ind.bollinger_upper:,.2f}` | Middle: `${ind.bollinger_middle:,.2f}` |",
            f"| **MACD Histogram** | `{ind.macd_hist:+.4f}` | {'Bullish Momentum' if ind.macd_hist > 0 else 'Bearish Pressure'} |",
            f"| **ATR (Volatility)** | `${ind.atr_14:,.2f}` | Daily Expected Range |",
            f"| **Volume Ratio** | `{ind.volume_ratio_24h:.2f}x` | vs 20-day Average |",
            "",
        ])

    lines.extend([
        "---",
        "",
        "## 🗣️ Multi-Agent Debate Transcript",
        "",
    ])

    for r in verdict.debate_rounds:
        lines.append(f"### 📍 Debate Round #{r.round_number}")
        lines.append(f"_{r.consensus_shift_notes}_\n")
        for thought in r.thoughts:
            role_emoji = "📐" if thought.role.value == "TECHNICAL" else "📰" if thought.role.value == "SENTIMENT" else "🛡️"
            lines.append(f"**{role_emoji} [{thought.callsign}] {thought.agent_name}** (`{thought.stance.value}`, {thought.confidence * 100:.0f}% confidence)")
            lines.append(f"> {thought.thesis}\n")
            if thought.key_points:
                lines.append("Key points:")
                for p in thought.key_points:
                    lines.append(f"- {p}")
            if thought.identified_risks:
                lines.append("Risks cited:")
                for rk in thought.identified_risks:
                    lines.append(f"- ⚠️ {rk}")
            lines.append("")

    lines.extend([
        "---",
        "_Dossier generated by AlphaSwarm (Autonomous Multi-Agent Market Intelligence Hub). Not financial advice._",
    ])

    return "\n".join(lines) + "\n"


def generate_html_report(verdict: ConsensusVerdict, market_data: MarketData) -> str:
    ind = market_data.indicators
    stance_color = (
        "#10b981" if "BULL" in verdict.final_stance.value
        else "#ef4444" if "BEAR" in verdict.final_stance.value
        else "#eab308"
    )

    debate_html = ""
    for r in verdict.debate_rounds:
        debate_html += f"<div class='round-header'>Round {r.round_number} &bull; {r.consensus_shift_notes}</div>"
        for t in r.thoughts:
            avatar = "📐" if t.role.value == "TECHNICAL" else "📰" if t.role.value == "SENTIMENT" else "🛡️"
            t_color = (
                "#10b981" if "BULL" in t.stance.value
                else "#ef4444" if "BEAR" in t.stance.value
                else "#eab308"
            )
            points_li = "".join(f"<li>{p}</li>" for p in t.key_points)
            risks_li = "".join(f"<li class='risk-item'>⚠️ {rk}</li>" for rk in t.identified_risks)

            debate_html += f"""
            <div class="agent-bubble">
                <div class="agent-meta">
                    <span class="avatar">{avatar}</span>
                    <div>
                        <strong>{t.agent_name}</strong> <span class="callsign">[{t.callsign}]</span>
                    </div>
                    <span class="badge" style="background: {t_color}22; color: {t_color}; border: 1px solid {t_color}66;">
                        {t.stance.value} &bull; {t.confidence * 100:.0f}%
                    </span>
                </div>
                <div class="thesis">{t.thesis}</div>
                <ul class="points-list">{points_li}{risks_li}</ul>
            </div>
            """

    rsi_str = f"{ind.rsi_14:.1f}" if ind else "N/A"
    trend_str = ind.trend_50_200 if ind else "N/A"
    atr_str = f"${ind.atr_14:,.2f}" if ind else "N/A"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AlphaSwarm Intelligence: {verdict.symbol}</title>
<style>
    body {{
        background: #090d16;
        color: #f1f5f9;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        margin: 0;
        padding: 40px 20px;
    }}
    .container {{
        max-width: 960px;
        margin: 0 auto;
        background: #111827;
        border: 1px solid #1f2937;
        border-radius: 16px;
        padding: 36px;
        box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.7);
    }}
    .header-bar {{
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 1px solid #1f2937;
        padding-bottom: 24px;
        margin-bottom: 24px;
    }}
    .ticker {{ font-size: 32px; font-weight: 800; color: #38bdf8; letter-spacing: -0.5px; }}
    .price {{ font-size: 28px; font-weight: 700; color: #f8fafc; }}
    .change {{ font-size: 14px; font-weight: 600; padding: 4px 8px; border-radius: 6px; }}
    .consensus-card {{
        background: #1e293b;
        border-left: 6px solid {stance_color};
        border-radius: 10px;
        padding: 24px;
        margin-bottom: 32px;
    }}
    .stance-title {{ font-size: 20px; font-weight: 800; color: {stance_color}; margin-bottom: 8px; }}
    .thesis-text {{ font-size: 15px; color: #cbd5e1; line-height: 1.6; }}
    .grid-stats {{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
        gap: 16px;
        margin-bottom: 32px;
    }}
    .stat-card {{
        background: #0f172a;
        border: 1px solid #1e293b;
        padding: 16px;
        border-radius: 8px;
    }}
    .stat-card .val {{ font-size: 20px; font-weight: 700; color: #38bdf8; margin-top: 4px; }}
    .stat-card .lbl {{ font-size: 11px; text-transform: uppercase; color: #64748b; font-weight: 600; }}
    .round-header {{
        font-size: 13px;
        color: #94a3b8;
        text-transform: uppercase;
        letter-spacing: 1px;
        margin: 24px 0 12px 0;
        font-weight: 700;
    }}
    .agent-bubble {{
        background: #0f172a;
        border: 1px solid #1e293b;
        border-radius: 12px;
        padding: 20px;
        margin-bottom: 16px;
    }}
    .agent-meta {{
        display: flex;
        align-items: center;
        gap: 12px;
        margin-bottom: 12px;
    }}
    .avatar {{ font-size: 24px; }}
    .callsign {{ color: #64748b; font-size: 12px; font-weight: 600; }}
    .badge {{
        margin-left: auto;
        font-size: 12px;
        font-weight: 700;
        padding: 4px 10px;
        border-radius: 6px;
    }}
    .thesis {{ font-size: 14px; color: #e2e8f0; line-height: 1.5; margin-bottom: 12px; }}
    .points-list {{ margin: 0; padding-left: 20px; font-size: 13px; color: #94a3b8; line-height: 1.6; }}
    .risk-item {{ color: #f87171; }}
</style>
</head>
<body>
<div class="container">
    <div class="header-bar">
        <div>
            <div class="ticker">⚡ ALPHASWARM // {verdict.symbol}</div>
            <div style="color: #64748b; font-size: 13px; margin-top: 4px;">Autonomous Multi-Agent Consensus Graph</div>
        </div>
        <div style="text-align: right;">
            <div class="price">${verdict.market_price:,.2f}</div>
            <span class="change" style="background: {'#10b98122' if market_data.change_24h_pct >= 0 else '#ef444422'}; color: {'#10b981' if market_data.change_24h_pct >= 0 else '#ef4444'};">
                {market_data.change_24h_pct:+.2f}% 24h
            </span>
        </div>
    </div>

    <div class="consensus-card">
        <div class="stance-title">CONSENSUS VERDICT: {verdict.final_stance.value} ({verdict.confidence_score}% Conviction)</div>
        <div class="thesis-text">{verdict.primary_thesis}</div>
    </div>

    <div class="grid-stats">
        <div class="stat-card">
            <div class="lbl">Key Invalidation</div>
            <div class="val" style="color: #f87171;">${verdict.key_invalidation_level:,.2f}</div>
        </div>
        <div class="stat-card">
            <div class="lbl">RSI (14-Day)</div>
            <div class="val">{rsi_str}</div>
        </div>
        <div class="stat-card">
            <div class="lbl">SMA 50 / 200 Trend</div>
            <div class="val" style="font-size: 15px;">{trend_str}</div>
        </div>
        <div class="stat-card">
            <div class="lbl">ATR Volatility</div>
            <div class="val">{atr_str}</div>
        </div>
    </div>

    <h2 style="font-size: 18px; color: #f1f5f9; border-bottom: 1px solid #1f2937; padding-bottom: 10px;">🗣️ Autonomous Agent Debate Stream</h2>
    {debate_html}
</div>
</body>
</html>
"""
